# This file was generated by GoReleaser. DO NOT EDIT.
class PygmyGo < Formula
  desc "amazee.io's local development helper tool"
  homepage "https://github.com/fubarhouse/pygmy-go"
  version "0.4.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/fubarhouse/pygmy-go/releases/download/v0.4.0/pygmy-go_0.4.0_darwin_amd64.tar.gz"
    sha256 "1cdbc8e0298701e9b22647d507bea72f1b3f666eff9be15f7f420637b22dae44"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/fubarhouse/pygmy-go/releases/download/v0.4.0/pygmy-go_0.4.0_linux_amd64.tar.gz"
      sha256 "a6b05d288f7267df4a4c4a22265b4a8bc069de81414736e0871e7498c25c0358"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fubarhouse/pygmy-go/releases/download/v0.4.0/pygmy-go_0.4.0_linux_arm64.tar.gz"
        sha256 "22e0605b1ba13f3913acfb6d3dcaacc6a2df3e7a167935b3b612ab9ff04d1e98"
      else
        url "https://github.com/fubarhouse/pygmy-go/releases/download/v0.4.0/pygmy-go_0.4.0_linux_armv6.tar.gz"
        sha256 "3fe30495d20dc98a3b6511aa0cd4d8b9ba79c8bac4b741ce044ca8fbce8387ee"
      end
    end
  end

  def install
    bin.install "pygmy-go"
  end

  test do
    system "#{bin}/pygmy-go version"
  end
end
