# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pygmy < Formula
  desc "Local development helper tool brought to you by amazee.io"
  homepage "https://github.com/pygmystack/pygmy"

  head do
    url "https://github.com/pygmystack/pygmy.git", branch: "main"
    depends_on "go" => :build if build.head?
  end

  on_macos do
    on_arm do
      url "https://github.com/pygmystack/pygmy/releases/download/v0.15.0/pygmy_0.15.0_darwin_arm64.tar.gz"
      sha256 "4469072a593ee723c95dafa3461357ca309c66b51709e2b00f17567561375c29"
    end
    on_intel do
      url "https://github.com/pygmystack/pygmy/releases/download/v0.15.0/pygmy_0.15.0_darwin_amd64.tar.gz"
      sha256 "9e8b4e7fd2f628964032b4d5c4b9a733a454477381d1d8eeb2a1555818ce1f54"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/pygmystack/pygmy/releases/download/v0.15.0/pygmy_0.15.0_linux_amd64.tar.gz"
      sha256 "93bbb8ea345fcf7bf019b7473fd62cb2b1af52dbd2485e27677fed684da76664"
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/pygmystack/pygmy/releases/download/v0.15.0/pygmy_0.15.0_linux_arm64.tar.gz"
        sha256 "3fe064cfe3e8444ade39d344922fb8f4c2572dd04b38d653d37ff153d3b6801c"
      end
    end
  end

  def install
    if build.head?
      system "go", "build", "-o", "pygmy"
      bin.install "pygmy"
    end
    bin.install "pygmy" => "pygmy"
  end

  test do
    system `bin/pygmy`, "version"
  end
end
