# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pygmy < Formula
  desc "amazee.io's local development helper tool"
  homepage "https://github.com/pygmystack/pygmy"
  version "0.9.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pygmystack/pygmy/releases/download/v0.10.0/pygmy_0.10.0_darwin_arm64.tar.gz"
      sha256 "22b1ef36efdc09822b21ad367c028d7ead00260605ae9acfd5df0aa1100568ca"

      def install
        bin.install "pygmy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pygmystack/pygmy/releases/download/v0.10.0/pygmy_0.10.0_darwin_amd64.tar.gz"
      sha256 "b3c171705db780dcd42a034ffb05123c11279262b38be0ee0a713a94717c6410"

      def install
        bin.install "pygmy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pygmystack/pygmy/releases/download/v0.10.0/pygmy_0.10.0_linux_amd64.tar.gz"
      sha256 "881fdccea53307270eb1ff8de1038b4e84039a3d4fa78f8c86070016d53a139e"

      def install
        bin.install "pygmy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pygmystack/pygmy/releases/download/v0.10.0/pygmy_0.10.0_linux_arm64.tar.gz"
      sha256 "f48d6b5fa93c46c7fe2a785a4dfb286ba53e9213e4c4dd889af1f536c7aa736a"

      def install
        bin.install "pygmy"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pygmystack/pygmy/releases/download/v0.10.0/pygmy_0.10.0_linux_arm.tar.gz"
      sha256 "440ae26e08fa9f34b33dde9047b766091d50ba116db0a6dbaf540f876c322ad8"

      def install
        bin.install "pygmy"
      end
    end
  end

  test do
    system "#{bin}/pygmy version"
  end
end
