name: Brew Audit

on:
  push:
    branches: [main, formula/fixes]
  pull_request:
    branches: [main, formula/fixes]

jobs:
  audit:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          brew update
          brew tap homebrew/core

      - name: Audit formula
        run: brew audit --strict --online "./Formula/pygmy.rb"

      - name: Test formula
        run: brew install --build-from-source "./Formula/pygmy.rb"
